version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest

      #- image: mysql:latest
      #  name: mysqltest
      #  commmand: --default-authentication-plugin=mysql_native_password
      #  environment:
      #    MYSQL_ALLOW_EMPTY_PASSWORD: yes

      #- image: vikramchauhan/mysqlcli:latest

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker

      #- run:
       #   name: Wait for db
        #  command: dockerize -wait tcp://mysqltest:3306 -timeout 120s

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            cp mysqlbackup/cfg/sample_docker_mysqlbackup.json mysqlbackup/cfg/mysqlbackup.json

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            docker run -d --network --name=mysqltest -p 3306:3306 -e "MYSQL_ALLOW_EMPTY_PASSWORD=yes" mysql:latest \
            --default-authentication-plugin=mysql_native_password
            docker logs mysqltest
            dockerize -wait tcp://0.0.0.0:3306 -timeout 60s
            docker logs mysqltest
            pytest -q .tests/*.py

      - store_artifacts:
          path: test-reports
          destination: test-reports